/**
 * Front-end view of the API contract.
 *
 * The canonical types are generated by ``pnpm gen:types`` from the
 * live FastAPI ``/openapi.json`` into ``lib/api-types.ts``. This file
 * re-exports the most-used names with friendlier aliases and adds a
 * couple of UI-only shapes (``StreamEvent``, ``ChatTurnViewModel``)
 * that don't exist on the backend.
 */

// ---------------------------------------------------------------------------
// Request / response — mirror copilot.main.AskRequest / AskResponse
// ---------------------------------------------------------------------------

export type ResumeDecision = "approve" | "reject";

export interface AskRequest {
  question?: string;
  conversation_id?: string;
  resume?: ResumeDecision;
}

export type AskStatus = "ok" | "pending_confirmation";

export type ChartKind = "kpi" | "bar" | "line" | "grouped_bar" | "table";

export interface MetricHighlight {
  label: string;
  value: number;
  format?: string;
}

export interface Insight {
  headline: string;
  bullets: string[];
  metric_highlights: MetricHighlight[];
}

export interface PendingRisk {
  sql: string;
  total_cost: number;
  threshold: number;
  reason: string;
}

export interface CostBreakdown {
  llm_calls: number;
  embedding_calls: number;
  db_explain_calls: number;
  db_select_calls: number;
  est_tokens_in: number;
  est_tokens_out: number;
  est_usd: number;
}

// Phase 1.1 — coverage gate & schema explorer envelope.
export type Intent = "data" | "chitchat" | "schema_explore" | "investigate";
export type CoverageVerdict = "ok" | "refuse" | "explore";

export interface CoverageTopic {
  name: string;
  tables: string[];
  summary: string;
}

export interface Coverage {
  verdict: CoverageVerdict;
  // Always present, sometimes empty on the ``ok`` branch.
  reason?: string;
  // Present on both ``refuse`` (gate-detected gaps) and ``ok`` (empty).
  missing_concepts?: string[];
  // The user-facing one-liner. ``refuse`` and ``explore`` always set it;
  // ``ok`` leaves it absent.
  headline?: string;
  // Bullet observations — refuse path only.
  bullets?: string[];
  // Clickable starter questions. Present on ``refuse`` and ``explore``.
  suggested_questions?: string[];
  // Schema tour — explore branch only.
  topics?: CoverageTopic[];
}

export interface AskResponse {
  answer: string;
  conversation_id: string;
  turn_index: number;
  sql: string | null;
  rows: Array<Record<string, unknown>> | null;
  row_count: number | null;
  error: string | null;
  attempts: number;
  attempts_history?: Array<Record<string, unknown>> | null;
  status: AskStatus;
  pending_risk: PendingRisk | null;
  insight: Insight | null;
  chart_kind: ChartKind | null;
  // Vega-Lite v5 spec. Typed as ``unknown`` JSON-shape because
  // ``react-vega`` ingests it as-is; the front-end never inspects
  // individual fields.
  chart_spec: Record<string, unknown> | null;
  cost: CostBreakdown | null;
  // Phase 1.1 — only populated on the two new branches.
  intent: Intent | null;
  coverage: Coverage | null;
}

// ---------------------------------------------------------------------------
// Streaming events — mirror what /ask/stream emits over SSE
// ---------------------------------------------------------------------------

export type StreamEventName = "phase" | "pending_confirmation" | "done" | "error";

export interface PhaseEvent {
  type: "phase";
  node: string;
  diff: Record<string, unknown>;
  internal: boolean;
}

export interface PendingConfirmationEvent {
  type: "pending_confirmation";
  conversation_id: string;
  pending_risk: PendingRisk;
}

export interface DoneEvent {
  type: "done";
  response: AskResponse;
}

export interface ErrorEvent {
  type: "error";
  detail: string;
  errorType: string;
}

export type StreamEvent = PhaseEvent | PendingConfirmationEvent | DoneEvent | ErrorEvent;

// ---------------------------------------------------------------------------
// UI-only shapes (don't exist on the backend)
// ---------------------------------------------------------------------------

/** One row in the chat history panel. */
export interface ChatTurnViewModel {
  /** Sequential ID assigned client-side so React can ``key`` consistently. */
  id: string;
  /** What the user typed. ``null`` on a "resume" turn that has no question. */
  question: string | null;
  /** Phase events seen during this turn, in arrival order. */
  phases: PhaseEvent[];
  /** Populated when the turn ends in a normal answer. */
  result: AskResponse | null;
  /** Populated when the turn ends paused at the HITL gate. */
  pending: PendingConfirmationEvent | null;
  /** Populated when the turn ended with a stream-level error. */
  error: ErrorEvent | null;
}
