"""Agent state — the single source of truth that flows through the graph.

LangGraph executes a *graph of nodes*. Each node is a Python function
that receives the current state, optionally mutates it, and returns the
fields it changed. LangGraph then merges those changes back into the
state and routes execution to the next node.

Because state is a TypedDict, IDEs and mypy can verify that every field
read or written is spelled correctly.

The ``messages`` field is special: ``Annotated[..., add_messages]`` tells
LangGraph to *append* incoming messages to the existing list rather than
replace it. This pattern (a "reducer") is how LangGraph supports
chat-style accumulating state without forcing every node to manually
preserve history.
"""

from __future__ import annotations

from typing import Annotated, TypedDict

from langgraph.graph.message import add_messages


class AgentState(TypedDict, total=False):
    """State carried through the agent graph.

    ``total=False`` means every key is optional; nodes populate fields
    incrementally as the agent makes progress.
    """

    # Conversation history. The ``add_messages`` reducer concatenates
    # any messages a node returns onto whatever was there before.
    messages: Annotated[list, add_messages]

    # ---------- Inputs (set by the caller) ----------
    question: str
    """The original natural-language question from the user."""

    # ---------- Intermediate (filled by nodes as they run) ----------
    relevant_schema: str
    """Pruned database schema fed to the LLM (set by the schema retriever)."""

    sql: str
    """SQL query generated by the LLM."""

    sql_result: list[dict]
    """Rows returned by executing the SQL."""

    error: str
    """Error message if any node fails (used by the self-healing loop)."""

    retry_count: int
    """How many times we have retried after an error."""

    # ---------- Outputs (read by the caller) ----------
    answer: str
    """Final natural-language answer presented to the user."""
