"""Agent state — the single source of truth that flows through the graph.

LangGraph executes a *graph of nodes*. Each node is a Python function
that receives the current state, optionally mutates it, and returns the
fields it changed. LangGraph then merges those changes back into the
state and routes execution to the next node.

Because state is a TypedDict, IDEs and mypy can verify that every field
read or written is spelled correctly.

The ``messages`` field is special: ``Annotated[..., add_messages]`` tells
LangGraph to *append* incoming messages to the existing list rather than
replace it. This pattern (a "reducer") is how LangGraph supports
chat-style accumulating state without forcing every node to manually
preserve history.
"""

from __future__ import annotations

import operator
from typing import Annotated, Any, Literal, TypedDict

from langgraph.graph.message import add_messages

Intent = Literal["data", "chitchat"]
"""Top-level intent. Decided by ``classify_intent_node`` and used by
``route_after_classify`` to branch the graph."""


ErrorClass = Literal["unsafe_sql", "execution_failed", "fatal"]
"""Categorisation of a node failure. Used by ``can_retry`` to decide
whether the agent loops back to ``generate_sql`` or terminates with a
user-facing error.

* ``unsafe_sql``        — sqlglot rejected the SQL (DROP / write op /
                          stacked statements). LLM rewrite often fixes
                          a misread of the question.
* ``execution_failed``  — sqlglot accepted the SQL but Postgres did
                          not (typo in column / table name, bad JOIN
                          condition). LLM is excellent at fixing these
                          when shown the error message.
* ``fatal``             — anything else (network, programmer error,
                          internal exception). We do not retry.
"""


class Attempt(TypedDict):
    """One pass through ``generate_sql -> validate_sql -> execute_sql``.

    Each failed attempt appends a record to ``state.attempts`` so the
    next ``generate_sql`` call can see what was tried and why it
    failed, and so routers can count failures by class.
    """

    sql: str
    error: str
    error_class: ErrorClass


class AgentState(TypedDict, total=False):
    """State carried through the agent graph.

    ``total=False`` means every key is optional; nodes populate fields
    incrementally as the agent makes progress.
    """

    # Conversation history. The ``add_messages`` reducer concatenates
    # any messages a node returns onto whatever was there before.
    messages: Annotated[list[Any], add_messages]

    # ---------- Inputs (set by the caller) ----------
    question: str
    """The original natural-language question from the user."""

    # ---------- Routing ----------
    intent: Intent
    """Whether the question needs SQL (``data``) or just a friendly
    reply (``chitchat``). Set by ``classify_intent_node``."""

    # ---------- Intermediate (filled by nodes as they run) ----------
    relevant_schema: str
    """Pruned database schema fed to the LLM (set by the schema retriever)."""

    sql: str
    """SQL query generated by the LLM."""

    sql_result: list[dict[str, Any]]
    """Rows returned by executing the SQL."""

    row_count: int
    """Number of rows returned by ``execute_sql_node`` (separate from
    ``len(sql_result)`` so a future streaming executor can populate it
    cheaply)."""

    error: str
    """Error message of the LATEST failure. ``generate_sql`` clears it
    on retry, so routers can rely on a non-empty value to mean
    'something went wrong in the run that just finished'."""

    attempts: Annotated[list[Attempt], operator.add]
    """Append-only history of failed attempts. Reducer is
    ``operator.add`` so any node returning ``{"attempts": [Attempt(...)]}``
    gets concatenated rather than overwritten. The list also serves as
    the retry counter — see ``can_retry`` in ``nodes.py``."""

    retry_count: int
    """Legacy field from week 2; superseded by ``attempts``. Kept for
    backwards compatibility with any external observer that read it."""

    # ---------- Outputs (read by the caller) ----------
    answer: str
    """Final natural-language answer presented to the user."""
